name: Bug report
description: Report a reproducible bug in fedramp-docs-mcp
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug and expected behavior.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Include exact steps or commands to reproduce the problem.
      placeholder: |
        1. Run ...
        2. Call tool ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide runtime details.
      placeholder: |
        OS:
        Node.js version:
        fedramp-docs-mcp version:
        MCP client:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      description: Paste relevant logs or stack traces.
      render: shell
    validations:
      required: false
