name: Feature request
description: Propose an enhancement to fedramp-docs-mcp
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the current limitation or pain point.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior or interface you want.
      placeholder: Describe the desired feature and user experience.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List alternative approaches you considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add links, examples, or prior art.
    validations:
      required: false
